# Generated by Django 3.2.8 on 2021-10-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_breakfast_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='todo/static/breakfasts'),
        ),
    ]
